# https://quarto.org/docs/projects/quarto-projects.html
project:
  type: website
  output-dir: ../_site

# https://quarto.org/docs/websites/#config-file
# https://quarto.org/docs/reference/projects/websites.html
website:
  title: ABM examples
  repo-url: https://github.com/ntumitolab/jl-abm
  back-to-top-navigation: true
  navbar:
    search: true
    tools:
      - icon: github
        href: https://github.com/ntumitolab/jl-abm
        text: GitHub repo
  sidebar:
    style: docked
    contents: auto

# https://quarto.org/docs/output-formats/html-basics.html
format:
  html:
    theme:
      light: flatly
      dark: darkly
    grid:
      sidebar-width: 350px
    toc: true
    css: styles.css

# Default options
# notebook-links: true

# Execution
# execute:
#   cache: true
# engines: ['julia']
